-- ==============================================================================
-- SCRIPT PARA CREAR TABLA DE PEDIDOS (EJECUTAR EN SUPABASE SQL EDITOR)
-- ==============================================================================

-- 1. Crear Tabla de Pedidos
create table public.orders (
  id bigint generated by default as identity primary key,
  client_name text not null,
  client_phone text,
  delivery_address text,
  delivery_date date not null, -- Fecha de entrega
  delivery_time time,          -- Hora de entrega
  items_summary text,          -- "Ramo de Rosas + Chocolate"
  total_amount numeric(10, 2) default 0,
  status text not null default 'pendiente', -- 'pendiente', 'en_proceso', 'en_ruta', 'entregado', 'cancelado'
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Habilitar RLS
alter table public.orders enable row level security;

-- 3. Crear Políticas de Seguridad (Permisivas para el Admin)
-- NOTA: Al igual que en inventario, usamos permisos abiertos 'public' protegido solo por la ruta de admin de la app.

-- Permitir SELECT (Leer)
create policy "Leer todos los pedidos"
on public.orders for select
to public
using (true);

-- Permitir INSERT (Crear)
create policy "Crear pedidos"
on public.orders for insert
to public
with check (true);

-- Permitir UPDATE (Editar/Cambiar estado)
create policy "Actualizar pedidos"
on public.orders for update
to public
using (true);

-- Permitir DELETE (Eliminar)
create policy "Eliminar pedidos"
on public.orders for delete
to public
using (true);

-- Confirmación
select 'Tabla de pedidos creada correctamente.' as resultado;
