-- 1. Tabla de Categorías
create table public.categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Tabla de Productos
create table public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  price numeric(10, 2) not null,
  category_id bigint references public.categories(id) on delete set null,
  image_url text, -- URL de la imagen (puede ser de Unsplash o Storage)
  description text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Datos iniciales (Categorías) - Opcional
insert into public.categories (name) values 
('Amor'), 
('Cumpleaños'), 
('Condolencias'), 
('Aniversario'), 
('Detalles')
on conflict do nothing;

-- 4. Habilitar seguridad (RLS) - Opcional por ahora, pero recomendado
alter table public.products enable row level security;
alter table public.categories enable row level security;

-- Políticas de lectura (Público puede ver)
create policy "Productos públicos" on public.products for select using (true);
create policy "Categorias públicas" on public.categories for select using (true);

-- Políticas de escritura (Solo autenticados/anon para dev)
-- NOTA: Para producción, deberías restringir esto solo al admin.
-- Por ahora permitiremos insert/update para que funcione el panel sin autenticación compleja de Supabase.
create policy "Admin Insert Productos" on public.products for insert with check (true);
create policy "Admin Update Productos" on public.products for update using (true);
create policy "Admin Delete Productos" on public.products for delete using (true);

create policy "Admin Insert Categorias" on public.categories for insert with check (true);
